# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

video-sync=display-resample

# Tell mpv to save screenshots to the Windows Pictures folder
# The "~/" shortcut automatically maps to your Windows User folder (e.g., C:\Users\Username\)
screenshot-directory="~/Pictures/ss"

# Optional: Set the image format and a nice naming template
screenshot-format=png
screenshot-template="mpv-ss-%F-%wHh%wMm%wSs%wTt"


save-position-on-quit=yes


# Optimized shaders for higher-end GPU: Mode A (HQ)
# glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"


# Forces the use of the GPU for video output
vo=gpu

# Enables hardware decoding. 'auto-safe' is recommended as it falls back to CPU if the GPU doesn't support the video codec.
hwdec=auto-safe

# (Optional) If you have a powerful dGPU, this profile improves video scaling and rendering quality.
profile=gpu-hq